import { HttpClient } from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Country, State } from '../interfaces/country.interface';
import { Observable } from 'rxjs/internal/Observable';
import { of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class CountrySelectBar {
  http = inject(HttpClient);
  private apiUrl = 'https://restcountries.com/v3.1';
  
  getCountries(): Observable<Country[]> {
    const url = `${this.apiUrl}/all?fields=name,cca2,borders`;
    return this.http.get<Country[]>(url);
  } 
  
  getStatesByCountry(countryCode: string): Observable<State[]> {
    const states = this.statesData[countryCode] || [];
    return of(states);
  }

  private statesData: { [key: string]: State[] } = {
    'EC': [
      { id: 1, name: 'Azuay', state_code: 'A' },
      { id: 2, name: 'Bolívar', state_code: 'B' },
      { id: 3, name: 'Cañar', state_code: 'F' },
      { id: 4, name: 'Carchi', state_code: 'C' },
      { id: 5, name: 'Chimborazo', state_code: 'H' },
      { id: 6, name: 'Cotopaxi', state_code: 'X' },
      { id: 7, name: 'El Oro', state_code: 'O' },
      { id: 8, name: 'Esmeraldas', state_code: 'E' },
      { id: 9, name: 'Galápagos', state_code: 'W' },
      { id: 10, name: 'Guayas', state_code: 'G' },
      { id: 11, name: 'Imbabura', state_code: 'I' },
      { id: 12, name: 'Loja', state_code: 'L' },
      { id: 13, name: 'Los Ríos', state_code: 'R' },
      { id: 14, name: 'Manabí', state_code: 'M' },
      { id: 15, name: 'Morona Santiago', state_code: 'S' },
      { id: 16, name: 'Napo', state_code: 'N' },
      { id: 17, name: 'Orellana', state_code: 'D' },
      { id: 18, name: 'Pastaza', state_code: 'Y' },
      { id: 19, name: 'Pichincha', state_code: 'P' },
      { id: 20, name: 'Santa Elena', state_code: 'SE' },
      { id: 21, name: 'Santo Domingo de los Tsáchilas', state_code: 'SD' },
      { id: 22, name: 'Sucumbíos', state_code: 'U' },
      { id: 23, name: 'Tungurahua', state_code: 'T' },
      { id: 24, name: 'Zamora Chinchipe', state_code: 'Z' }
    ],
    'US': [
      { id: 1, name: 'Alabama', state_code: 'AL' },
      { id: 2, name: 'Alaska', state_code: 'AK' },
      { id: 3, name: 'Arizona', state_code: 'AZ' },
      { id: 4, name: 'Arkansas', state_code: 'AR' },
      { id: 5, name: 'California', state_code: 'CA' },
      { id: 6, name: 'Colorado', state_code: 'CO' },
      { id: 7, name: 'Connecticut', state_code: 'CT' },
      { id: 8, name: 'Delaware', state_code: 'DE' },
      { id: 9, name: 'Florida', state_code: 'FL' },
      { id: 10, name: 'Georgia', state_code: 'GA' },
      { id: 11, name: 'Hawaii', state_code: 'HI' },
      { id: 12, name: 'Idaho', state_code: 'ID' },
      { id: 13, name: 'Illinois', state_code: 'IL' },
      { id: 14, name: 'Indiana', state_code: 'IN' },
      { id: 15, name: 'Iowa', state_code: 'IA' },
      { id: 16, name: 'Kansas', state_code: 'KS' },
      { id: 17, name: 'Kentucky', state_code: 'KY' },
      { id: 18, name: 'Louisiana', state_code: 'LA' },
      { id: 19, name: 'Maine', state_code: 'ME' },
      { id: 20, name: 'Maryland', state_code: 'MD' },
      { id: 21, name: 'Massachusetts', state_code: 'MA' },
      { id: 22, name: 'Michigan', state_code: 'MI' },
      { id: 23, name: 'Minnesota', state_code: 'MN' },
      { id: 24, name: 'Mississippi', state_code: 'MS' },
      { id: 25, name: 'Missouri', state_code: 'MO' },
      { id: 26, name: 'Montana', state_code: 'MT' },
      { id: 27, name: 'Nebraska', state_code: 'NE' },
      { id: 28, name: 'Nevada', state_code: 'NV' },
      { id: 29, name: 'New Hampshire', state_code: 'NH' },
      { id: 30, name: 'New Jersey', state_code: 'NJ' },
      { id: 31, name: 'New Mexico', state_code: 'NM' },
      { id: 32, name: 'New York', state_code: 'NY' },
      { id: 33, name: 'North Carolina', state_code: 'NC' },
      { id: 34, name: 'North Dakota', state_code: 'ND' },
      { id: 35, name: 'Ohio', state_code: 'OH' },
      { id: 36, name: 'Oklahoma', state_code: 'OK' },
      { id: 37, name: 'Oregon', state_code: 'OR' },
      { id: 38, name: 'Pennsylvania', state_code: 'PA' },
      { id: 39, name: 'Rhode Island', state_code: 'RI' },
      { id: 40, name: 'South Carolina', state_code: 'SC' },
      { id: 41, name: 'South Dakota', state_code: 'SD' },
      { id: 42, name: 'Tennessee', state_code: 'TN' },
      { id: 43, name: 'Texas', state_code: 'TX' },
      { id: 44, name: 'Utah', state_code: 'UT' },
      { id: 45, name: 'Vermont', state_code: 'VT' },
      { id: 46, name: 'Virginia', state_code: 'VA' },
      { id: 47, name: 'Washington', state_code: 'WA' },
      { id: 48, name: 'West Virginia', state_code: 'WV' },
      { id: 49, name: 'Wisconsin', state_code: 'WI' },
      { id: 50, name: 'Wyoming', state_code: 'WY' }
    ],
    'MX': [
      { id: 1, name: 'Aguascalientes', state_code: 'AGU' },
      { id: 2, name: 'Baja California', state_code: 'BCN' },
      { id: 3, name: 'Baja California Sur', state_code: 'BCS' },
      { id: 4, name: 'Campeche', state_code: 'CAM' },
      { id: 5, name: 'Chiapas', state_code: 'CHP' },
      { id: 6, name: 'Chihuahua', state_code: 'CHH' },
      { id: 7, name: 'Ciudad de México', state_code: 'CMX' },
      { id: 8, name: 'Coahuila', state_code: 'COA' },
      { id: 9, name: 'Colima', state_code: 'COL' },
      { id: 10, name: 'Durango', state_code: 'DUR' },
      { id: 11, name: 'Guanajuato', state_code: 'GUA' },
      { id: 12, name: 'Guerrero', state_code: 'GRO' },
      { id: 13, name: 'Hidalgo', state_code: 'HID' },
      { id: 14, name: 'Jalisco', state_code: 'JAL' },
      { id: 15, name: 'México', state_code: 'MEX' },
      { id: 16, name: 'Michoacán', state_code: 'MIC' },
      { id: 17, name: 'Morelos', state_code: 'MOR' },
      { id: 18, name: 'Nayarit', state_code: 'NAY' },
      { id: 19, name: 'Nuevo León', state_code: 'NLE' },
      { id: 20, name: 'Oaxaca', state_code: 'OAX' },
      { id: 21, name: 'Puebla', state_code: 'PUE' },
      { id: 22, name: 'Querétaro', state_code: 'QUE' },
      { id: 23, name: 'Quintana Roo', state_code: 'ROO' },
      { id: 24, name: 'San Luis Potosí', state_code: 'SLP' },
      { id: 25, name: 'Sinaloa', state_code: 'SIN' },
      { id: 26, name: 'Sonora', state_code: 'SON' },
      { id: 27, name: 'Tabasco', state_code: 'TAB' },
      { id: 28, name: 'Tamaulipas', state_code: 'TAM' },
      { id: 29, name: 'Tlaxcala', state_code: 'TLA' },
      { id: 30, name: 'Veracruz', state_code: 'VER' },
      { id: 31, name: 'Yucatán', state_code: 'YUC' },
      { id: 32, name: 'Zacatecas', state_code: 'ZAC' }
    ],
    'CO': [
      { id: 1, name: 'Amazonas', state_code: 'AMA' },
      { id: 2, name: 'Antioquia', state_code: 'ANT' },
      { id: 3, name: 'Arauca', state_code: 'ARA' },
      { id: 4, name: 'Atlántico', state_code: 'ATL' },
      { id: 5, name: 'Bogotá D.C.', state_code: 'DC' },
      { id: 6, name: 'Bolívar', state_code: 'BOL' },
      { id: 7, name: 'Boyacá', state_code: 'BOY' },
      { id: 8, name: 'Caldas', state_code: 'CAL' },
      { id: 9, name: 'Caquetá', state_code: 'CAQ' },
      { id: 10, name: 'Casanare', state_code: 'CAS' },
      { id: 11, name: 'Cauca', state_code: 'CAU' },
      { id: 12, name: 'Cesar', state_code: 'CES' },
      { id: 13, name: 'Chocó', state_code: 'CHO' },
      { id: 14, name: 'Córdoba', state_code: 'COR' },
      { id: 15, name: 'Cundinamarca', state_code: 'CUN' },
      { id: 16, name: 'Guainía', state_code: 'GUA' },
      { id: 17, name: 'Guaviare', state_code: 'GUV' },
      { id: 18, name: 'Huila', state_code: 'HUI' },
      { id: 19, name: 'La Guajira', state_code: 'LAG' },
      { id: 20, name: 'Magdalena', state_code: 'MAG' },
      { id: 21, name: 'Meta', state_code: 'MET' },
      { id: 22, name: 'Nariño', state_code: 'NAR' },
      { id: 23, name: 'Norte de Santander', state_code: 'NSA' },
      { id: 24, name: 'Putumayo', state_code: 'PUT' },
      { id: 25, name: 'Quindío', state_code: 'QUI' },
      { id: 26, name: 'Risaralda', state_code: 'RIS' },
      { id: 27, name: 'San Andrés y Providencia', state_code: 'SAP' },
      { id: 28, name: 'Santander', state_code: 'SAN' },
      { id: 29, name: 'Sucre', state_code: 'SUC' },
      { id: 30, name: 'Tolima', state_code: 'TOL' },
      { id: 31, name: 'Valle del Cauca', state_code: 'VAC' },
      { id: 32, name: 'Vaupés', state_code: 'VAU' },
      { id: 33, name: 'Vichada', state_code: 'VID' }
    ],
    'PE': [
      { id: 1, name: 'Amazonas', state_code: 'AMA' },
      { id: 2, name: 'Áncash', state_code: 'ANC' },
      { id: 3, name: 'Apurímac', state_code: 'APU' },
      { id: 4, name: 'Arequipa', state_code: 'ARE' },
      { id: 5, name: 'Ayacucho', state_code: 'AYA' },
      { id: 6, name: 'Cajamarca', state_code: 'CAJ' },
      { id: 7, name: 'Callao', state_code: 'CAL' },
      { id: 8, name: 'Cusco', state_code: 'CUS' },
      { id: 9, name: 'Huancavelica', state_code: 'HUV' },
      { id: 10, name: 'Huánuco', state_code: 'HUC' },
      { id: 11, name: 'Ica', state_code: 'ICA' },
      { id: 12, name: 'Junín', state_code: 'JUN' },
      { id: 13, name: 'La Libertad', state_code: 'LAL' },
      { id: 14, name: 'Lambayeque', state_code: 'LAM' },
      { id: 15, name: 'Lima', state_code: 'LIM' },
      { id: 16, name: 'Loreto', state_code: 'LOR' },
      { id: 17, name: 'Madre de Dios', state_code: 'MDD' },
      { id: 18, name: 'Moquegua', state_code: 'MOQ' },
      { id: 19, name: 'Pasco', state_code: 'PAS' },
      { id: 20, name: 'Piura', state_code: 'PIU' },
      { id: 21, name: 'Puno', state_code: 'PUN' },
      { id: 22, name: 'San Martín', state_code: 'SAM' },
      { id: 23, name: 'Tacna', state_code: 'TAC' },
      { id: 24, name: 'Tumbes', state_code: 'TUM' },
      { id: 25, name: 'Ucayali', state_code: 'UCA' }
    ],
    'AR': [
      { id: 1, name: 'Buenos Aires', state_code: 'B' },
      { id: 2, name: 'Ciudad Autónoma de Buenos Aires', state_code: 'C' },
      { id: 3, name: 'Catamarca', state_code: 'K' },
      { id: 4, name: 'Chaco', state_code: 'H' },
      { id: 5, name: 'Chubut', state_code: 'U' },
      { id: 6, name: 'Córdoba', state_code: 'X' },
      { id: 7, name: 'Corrientes', state_code: 'W' },
      { id: 8, name: 'Entre Ríos', state_code: 'E' },
      { id: 9, name: 'Formosa', state_code: 'P' },
      { id: 10, name: 'Jujuy', state_code: 'Y' },
      { id: 11, name: 'La Pampa', state_code: 'L' },
      { id: 12, name: 'La Rioja', state_code: 'F' },
      { id: 13, name: 'Mendoza', state_code: 'M' },
      { id: 14, name: 'Misiones', state_code: 'N' },
      { id: 15, name: 'Neuquén', state_code: 'Q' },
      { id: 16, name: 'Río Negro', state_code: 'R' },
      { id: 17, name: 'Salta', state_code: 'A' },
      { id: 18, name: 'San Juan', state_code: 'J' },
      { id: 19, name: 'San Luis', state_code: 'D' },
      { id: 20, name: 'Santa Cruz', state_code: 'Z' },
      { id: 21, name: 'Santa Fe', state_code: 'S' },
      { id: 22, name: 'Santiago del Estero', state_code: 'G' },
      { id: 23, name: 'Tierra del Fuego', state_code: 'V' },
      { id: 24, name: 'Tucumán', state_code: 'T' }
    ],
    'CL': [
      { id: 1, name: 'Arica y Parinacota', state_code: 'AP' },
      { id: 2, name: 'Tarapacá', state_code: 'TA' },
      { id: 3, name: 'Antofagasta', state_code: 'AN' },
      { id: 4, name: 'Atacama', state_code: 'AT' },
      { id: 5, name: 'Coquimbo', state_code: 'CO' },
      { id: 6, name: 'Valparaíso', state_code: 'VS' },
      { id: 7, name: 'Metropolitana de Santiago', state_code: 'RM' },
      { id: 8, name: "O'Higgins", state_code: 'LI' },
      { id: 9, name: 'Maule', state_code: 'ML' },
      { id: 10, name: 'Ñuble', state_code: 'NB' },
      { id: 11, name: 'Biobío', state_code: 'BI' },
      { id: 12, name: 'La Araucanía', state_code: 'AR' },
      { id: 13, name: 'Los Ríos', state_code: 'LR' },
      { id: 14, name: 'Los Lagos', state_code: 'LL' },
      { id: 15, name: 'Aysén', state_code: 'AI' },
      { id: 16, name: 'Magallanes', state_code: 'MA' }
    ],
    'VE': [
      { id: 1, name: 'Amazonas', state_code: 'Z' },
      { id: 2, name: 'Anzoátegui', state_code: 'B' },
      { id: 3, name: 'Apure', state_code: 'C' },
      { id: 4, name: 'Aragua', state_code: 'D' },
      { id: 5, name: 'Barinas', state_code: 'E' },
      { id: 6, name: 'Bolívar', state_code: 'F' },
      { id: 7, name: 'Carabobo', state_code: 'G' },
      { id: 8, name: 'Cojedes', state_code: 'H' },
      { id: 9, name: 'Delta Amacuro', state_code: 'Y' },
      { id: 10, name: 'Distrito Capital', state_code: 'A' },
      { id: 11, name: 'Falcón', state_code: 'I' },
      { id: 12, name: 'Guárico', state_code: 'J' },
      { id: 13, name: 'Lara', state_code: 'K' },
      { id: 14, name: 'Mérida', state_code: 'L' },
      { id: 15, name: 'Miranda', state_code: 'M' },
      { id: 16, name: 'Monagas', state_code: 'N' },
      { id: 17, name: 'Nueva Esparta', state_code: 'O' },
      { id: 18, name: 'Portuguesa', state_code: 'P' },
      { id: 19, name: 'Sucre', state_code: 'R' },
      { id: 20, name: 'Táchira', state_code: 'S' },
      { id: 21, name: 'Trujillo', state_code: 'T' },
      { id: 22, name: 'Vargas', state_code: 'X' },
      { id: 23, name: 'Yaracuy', state_code: 'U' },
      { id: 24, name: 'Zulia', state_code: 'V' }
    ]
  };
}
